# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def sharePod
    pod 'MJExtension'
end

target 'WidgetDD' do
  sharePod

end

target 'WidgetTest' do
  sharePod

end
